### ISSUE TITLE
Where is the best way to integrate with CustomCSSforFx

### ISSUE THREAD

**Issue by gabri25ele** [B00ze64/FF-Menu-Icon-Plus-CSS#10]
If we use completely Aris-t2's CustomCSSforFx, where is the best way to integrate with it?

**Comment by B00ze64** [comment]
I use that too, I do it this way:

At the TOP of my userChrome.css (before all of Aris's stuff) ->
```css
@import "./css/generalui/bookmark_icons_colorized.css";		/* Aris-t2 bookmarks folders [must appear BEFORE Menu Icon Plus] */
@import "./MipCss/mip_FuguePlus-Menus.css";			/* Firefox Menus  Fugue+ Theme */
@import "./MipCss/mip_FuguePlus-Panels.css";			/* Firefox Panels Fugue+ Theme */
@import "./MipCss/mip_worksheet-AddIconsToExtensions.css";	/**/
```

And then all of Aris's stuff below that, except of course bookmark_icons_colorized.css, since it is now the first thing in the userChrome.

Regards.
