### ISSUE TITLE
Remove import of FirefoxSVG

### ISSUE THREAD

**Issue by Speravir** [B00ze64/FF-Menu-Icon-Plus-CSS#11]
After you [according to release notes](https://github.com/B00ze64/FF-Menu-Icon-Plus-CSS/releases/tag/v2.6.8) removed support for the FirefoxSVG theme from v2.6.8 you also should remove its import possibility from `userChrome.css`  ([lines 72 + 73](https://github.com/B00ze64/FF-Menu-Icon-Plus-CSS/blob/ce1ab8fa760a9eb7c8ade975c67654dacdf078bf/chrome/userChrome.css#L72),[line 85](https://github.com/B00ze64/FF-Menu-Icon-Plus-CSS/blob/ce1ab8fa760a9eb7c8ade975c67654dacdf078bf/chrome/userChrome.css#L85)) and `userContent.css` ([line 66](https://github.com/B00ze64/FF-Menu-Icon-Plus-CSS/blob/ce1ab8fa760a9eb7c8ade975c67654dacdf078bf/chrome/userContent.css#L66)).

**Comment by B00ze64** [comment]
I pushed a commit to fix this, thanks, oops lol.
