### ISSUE TITLE
-moz-image-region does not exist any more

### ISSUE THREAD

**Issue by bege10** [B00ze64/FF-Menu-Icon-Plus-CSS#14]
Hello,
thank you for the new release.
`-moz-image-region` is no longer supported in Firefox and can simply be removed. It was only necessary for png files with many icons which is no longer supported. For single icon png files it is redundant.

**Comment by B00ze64** [comment]
Yeah, but since I use single images it's not a problem. I might have a few moz-image-region left in the code but they would be AUTO and benign since, again, I use only single images. Thanks for the heads-up though.
