### ISSUE TITLE
Rotate Icons on Hover & Action

### ISSUE THREAD

**Issue by ChasCB** [B00ze64/FF-Menu-Icon-Plus-CSS#16]
I am a very visual person and love lots and lots of icons. It has taken me a long time to find Menu-Icon-Plus as I use a pared down version of Aris-t2's CustomCSSforFx, along with my own userChrome css. Years ago in a far off galaxy I  used Mostly Crystal by CatThief, sadly she is gone now.

What I discovered years ago was a way to rotate icons on hover & active but not all icons. I just recently got the right click context menus [#contentAreaContextMenu] to work. But I am missing the elements for the main menubar (Firefox, File, Edit, View, History, Bookmarks, Tools, Window, Help) and the sidebar box.

I was wondering if you could incorporate this code into yours or provide me with the missing code to fore-fill my dreams?

Firefox for macOS 127.0.2
[CustomCSSforFx](https://github.com/Aris-t2/CustomCSSforFx) Public version 4.5.4

**My present code is:**

`/****************/
/* ROTATE ICONS */
/****************/

/*rotate icons 30deg on hover*/

#nav-bar toolbarbutton:hover > .toolbarbutton-badge-stack,
menupopup#contentAreaContextMenu menu:hover > .menu-iconic-left > .menu-iconic-icon,
menupopup#contentAreaContextMenu menuitem:hover > .menu-iconic-left > .menu-iconic-icon,
checkbox:hover > .checkbox-check,
menuitem:hover > hbox > .menu-iconic-icon,
toolbarbutton:hover > image,
button:hover > .button-box > .button-icon {
  transform: rotate(30deg) !important;
  -moz-transform: rotate(30deg) !important;
}

/*rotate icons 75deg on active (clicked)*/

#nav-bar toolbarbutton:active > .toolbarbutton-badge-stack,
menupopup#contentAreaContextMenu menu:active > .menu-iconic-left > .menu-iconic-icon,
menupopup#contentAreaContextMenu menuitem:active > .menu-iconic-left > .menu-iconic-icon,
checkbox:active > .checkbox-check,
menuitem:active > hbox > .menu-iconic-icon,
toolbarbutton:active > .toolbarbutton-icon,
button:active > .button-box > .button-icon  {
  transform: rotate(75deg) !important;
  -moz-transform: rotate(75deg) !important;
}

/*if it doesn't have this then the icons get swapped to the other side on hover*/

#nav-bar toolbarbutton > .toolbarbutton-badge-stack,
menupopup#contentAreaContextMenu menu > .menu-iconic-left > .menu-iconic-icon,
menupopup#contentAreaContextMenu menuitem > .menu-iconic-left > .menu-iconic-icon,
checkbox > .checkbox-check,
menuitem > hbox > .menu-iconic-icon,
toolbarbutton > .toolbarbutton-icon,
button > .button-box > .button-icon {
  transform: rotate(0) !important;
  -moz-transform: rotate(0) !important;
}
/**/`

**Comment by B00ze64** [comment]
Sorry I just noticed this. I don't plan to rotate the icons, sorry.
