### ISSUE TITLE
macOS FF compatiblity

### ISSUE THREAD

**Issue by ChasCB** [B00ze64/FF-Menu-Icon-Plus-CSS#17]
Will there be a macOS Firefox version release ?

**Comment by B00ze64** [comment]
I do not have access to MacOS, it could be compatible already, I have no idea.

**Comment by ChasCB** [comment]
Thanks.  With macOS Firefox I am running into a road block with iconising menu-mainmenu (File, Edit, View, History, Bookmarks, Tools, Window, Help. Though with the Bookmarks menu-mainmenu I have no trouble with the actual Folder icon and favicons. Using Browser Toolbox the menu-mainmenu id's and elements are quite convoluted. And pulling other peoples css code apart I can end up with over 100 lines or more (well done to you and other coders) which is not really what I want in a userChrome file. 
It is just a shame that Mostly Crystal by CatThief is no longer. Her code and icons were just so beautiful and easy to pull apart.

**Comment by B00ze64** [comment]
Closing since I do not have a Mac.
