### ISSUE TITLE
Support for Hamburger button menu?

### ISSUE THREAD

**Issue by Marvinoo** [B00ze64/FF-Menu-Icon-Plus-CSS#3]
Hello Sir,
Thank you for this awesome work. I'm new to all these Firefox customization and I just have got a question,
I like the (Silk) variation of these icons and I've these files installed properly :
`@import "./MipCss/mip_Silk-Menus.css";`
`@import "./MipCss/mip_override_CutCopyPaste-Silk.css";`
   But the Silk project doesn't theme the 'Web Developer' & 'About' menus _**from the Hamburger button**_. So will there be any support for them? THANK YOU so much.
![ovksaBJvy9](https://user-images.githubusercontent.com/45720537/94984431-1dc47600-054c-11eb-888e-107b6c10dfa7.png)![lheQGI7E28](https://user-images.githubusercontent.com/45720537/94984433-20bf6680-054c-11eb-8dcc-d1689de576e7.png)

**Comment by B00ze64** [comment]
Hi.

You don't need mip_override_CutCopyPaste-Silk.css if you are using mip_Silk-Menus.css.

The hamburger button is a "panel" and I have not done those yet. I don't use the button at all, so I am less inclined to rush to do it. I'll get to it eventually, it's on the todo list.

**Comment by B00ze64** [comment]
Since Proton is coming I'm not really working on the panels yet.
Get [appbutton_popup_more_icons.css](https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/css/appbutton/appbutton_popup_more_icons.css) for now, it's what I use and assist in maintaining.

**Comment by B00ze64** [comment]
Alright, FF89 is out, new panels are here. [This](https://github.com/black7375/Firefox-UI-Fix) project has CSS already made for adding icons to the panels. You can use that while I see about "borrowing" its code to use with the MIP icons...

**Comment by B00ze64** [comment]
v2.0 has the panels now.
