### ISSUE TITLE
A couple of icons missing from FF 87

### ISSUE THREAD

**Issue by glennpc** [B00ze64/FF-Menu-Icon-Plus-CSS#5]
The new FF 87.0a1 (2021-02-08) (64-bit) can use 2 icons under "Help". It is:

Check for Updates...

Task Manager

![nightly](https://user-images.githubusercontent.com/54756104/107257115-33144a00-69ef-11eb-93ec-126255e891b5.png)

**Comment by B00ze64** [comment]
Interesting, new options. Alright, I'll see about icons once I get FF87. Not sure I'll find something, we'll see. Thanks for reporting.

**Comment by B00ze64** [comment]
Well, Check For Updates appears to be a Nightly-Thing-Only, I do not have it in production FF. I've fixed everything else with v1.5.2. If you give me the ID of that menuitem, I can add an icon to it, open a new issue, Regards,

**Comment by glennpc** [comment]
Looks good on FF87. Thanks for the update! I just checked FF88 beta, and there are 2 that are missing on there:

Help > Report Site Issue...

![ff88](https://user-images.githubusercontent.com/54756104/112728041-7ca6ee80-8ee2-11eb-8b61-8478504265e3.png)

Close Multiple Tabs > Close Tabs to the Left

![ff88a](https://user-images.githubusercontent.com/54756104/112728042-7d3f8500-8ee2-11eb-8ee3-779aded804ec.png)
