### ISSUE TITLE
Firefox 88 Icons

### ISSUE THREAD

**Issue by glennpc** [B00ze64/FF-Menu-Icon-Plus-CSS#6]
Now that Firefox 88 has been released and no longer in beta, I have verified that 3 icons are missing as far as I can tell. I did a screenshot of them below.

**Close Tabs to the Left**

![Close Tabs to the Left](https://user-images.githubusercontent.com/54756104/115446432-1143fa00-a1cc-11eb-96b7-38e4ed52584f.png)

**Customize Toolbar**

![Customize Toolbar](https://user-images.githubusercontent.com/54756104/115446434-11dc9080-a1cc-11eb-81da-27dd63f6f1f8.png)
**Redo**
![Redo](https://user-images.githubusercontent.com/54756104/115446435-11dc9080-a1cc-11eb-8ffa-a029f192a548.png)

**Comment by B00ze64** [comment]
I'll take a look once 88 is pushed to me, thanks.

**Comment by B00ze64** [comment]
Alright, I downloaded it, confirmed, I'll work on it this week.

**Comment by B00ze64** [comment]
Should be resolved now.

**Comment by glennpc** [comment]
Thank you very much. Looks great! Who knows what they will do on future Firefox releases with Proton. For now, I will disable Proton on the next release. I'm testing the beta Fx89 and nightly 90 at the moment.

**Comment by B00ze64** [comment]
Glad to hear it.
