### ISSUE TITLE
Only 1 Icon Missing for FF 89

### ISSUE THREAD

**Issue by glennpc** [B00ze64/FF-Menu-Icon-Plus-CSS#7]
I have Proton disabled with FF 89. I also checked it on FF90, and the same New Tab is missing.
Starting with FF 91, won't be able to disable Proton any longer.

![New Tab](https://user-images.githubusercontent.com/54756104/120906080-56e94480-c60b-11eb-9e89-b3f2c84e7c78.png)

**Comment by B00ze64** [comment]
New Tab on the context menu for the Tab Bar (empty space) is a new option, so it does not have an icon yet.
I'll see about adding one.

**Comment by B00ze64** [comment]
Found several missing icons, should all be resolved with release 1.5.5.
