### ISSUE TITLE
Question about FF Menu Icon Plus CSS files and folders 

### ISSUE THREAD

**Issue by TW462** [B00ze64/FF-Menu-Icon-Plus-CSS#8]
Hi B00ze64,

A basic question I have to ask, I would like to use your FF-Menu-Icon-Plus-CSS files & folders for use with Aris-t2CustomCSSforFx. I know that I need to add the folders and css files to the Chrome folder. I created a couple of CSS files called my_userChrome.css & my_userContent.css that Aris-t2 recommends for any "special" CSS files and have that load with the userChrome.css & the userContent.css. Your MIP folders I added to the existing Chrome folder where everything is located.

I can't seem to get my menus and such to look remotely like your showing with the descriptions. It appears that I am missing something. I have that one command activated that you pointed out. I always have that activated.

Maybe you can point me in the right direction would be very helpful. If you need more information I will be glad to supply it. I have as my operating system Mac OS 11.4 (Big Sur) Firefox 89. Please advise.

Thank you in advance,
Thomas

**Comment by B00ze64** [comment]
Good day. Without a zip file of your Chrome folder, I cannot assist. Sorry.

**Comment by TW462** [comment]
Hi B00ze64,
Attached is my chrome.zip file. I left everything in default mode just to see what got changed/added. Hope the zip file helps. Let me know what you find and what I need to fix or change.

Thanks,
Thomas 

[chrome.zip](https://github.com/B00ze64/FF-Menu-Icon-Plus-CSS/files/6713467/chrome.zip)

**Comment by B00ze64** [comment]
Thanks, your "my_userChrome.css" is broken, you removed a slash which was delimiting a comment, see ->

![image](https://user-images.githubusercontent.com/15389810/123462218-8ae7d200-d5d9-11eb-89fe-58c970a71e2d.png)

**Comment by TW462** [comment]
Hi, I fixed the delimiting a comment problem. I am using your defaults to get started. Some other issues now show, attachment 1 shows what menu displays using your menu-icon-plusCSS. Attachment 2 is the open application menu from attachment 1when pulled down which displays the icons as expected. Attachment 3 only shows the menu selection without the icons. The other menu selections are the same, no icons only menu selections. Attachment 4 shows the bookmarks menu and with the icons. I am probably missing a command or something.

Thank you,

Thomas

**Comment by B00ze64** [comment]
Well, nice to see you've fixed it, works fine here, all the menus have icons, so I'll close the issue. Best Regards,

**Comment by TW462** [comment]
Hi,

I have a quick question, I have the pull down bookmarks menu able to display the icons when I use any of your icon sets such as Tango which I am using now.

I am unable to display the icons on the other pull down menus and context panel as you have shown on your web page. I have made your corrections per your last email.

Is there anything else I need to do or modify on the "about:config" files, or what to look for to have your icons displayed on the other menus? I am at a lost. Any and all suggestions are welcome.

Thank you in advance,

Thomas

**Comment by B00ze64** [comment]
I did not email you, I replied on Github, and all that was wrong in your whole Chrome folder was a comment that was not delimited. Once you (and I using your own userChrome) fixed that, everything worked, I tested it here with your Chrome setup. As for the different themes, all you need to do is un-comment the appropriate lines from the userChrome file I provide. Regards,

**Comment by TW462** [comment]
Hello,

Sorry to ask a question thru my email. Thank you for all you have done. Once again I want to thank you. I will ask thru Github from this point on if I have any questions.

Thanks,
Thomas

**Comment by TW462** [comment]
Hello B00ze64,

I am stumped as far as displaying icons in the menus even after making your correction. The bookmarks have all their icons displayed, whereas the other menus do not. The contextual menus has some. Please see the screenshots.

I am using Aris-t2/CustomCSSforFx customizations latest 4.0.0pre9. 

All of your testing has been on Windows 7/10 and not on a Macintosh. I'm on Macintosh 11.5 Big Sur. Should my results be the same?

1st screenshot= Bookmark menu
2nd screenshot=Tools menu
3rd screenshot=Contextual menu

Thank you in advance,
Thomas


![Screen Shot 2021-07-25 at 2 27 13 PM](https://user-images.githubusercontent.com/77515829/126914024-c52dbab1-32ec-4238-8acf-6db42c2c223e.png)
![Screen Shot 2021-07-25 at 2 27 25 PM](https://user-images.githubusercontent.com/77515829/126914025-2db2979c-c771-42a0-9fa7-dbf3b788a16c.png)
![Screen Shot 2021-07-25 at 2 27 37 PM](https://user-images.githubusercontent.com/77515829/126914026-74870154-ee79-481b-bc8a-de922bd65f38.png)

**Comment by B00ze64** [comment]
You do not have a single icon from Menu Icon Plus CSS enabled. The only icons you do have, are from Aris or extensions. I have no idea about MAC O/S but ::Before should be working; my guess is you are still not @import'ing the files correctly.
