### ISSUE TITLE
Menus are broken on Win10 on FF9x.

### ISSUE THREAD

**Issue by mzso** [B00ze64/FF-Menu-Icon-Plus-CSS#9]
Hi!

Text overlaps icons and text is missing.
Here's what's the toolbar menu is like:
![kép](https://user-images.githubusercontent.com/4479090/144711293-b308ce09-00f1-412b-a96d-4bc02dd6e84b.png)

**Comment by B00ze64** [comment]
Hmm, big mess! I'm still on 94, will have to wait for 95 to come out to see what they changed. Thanks for letting me know.

**Comment by B00ze64** [comment]
Well, I updated to v95, found some things to fix, but nothing as bad as your screenshot. You are showing me a screenshot of the context menu for an icon on the toolbar. That menu still works just fine for me. Is it possible that Mozilla made big changes to the menus but only for Windows 10? I am using Windows 7, my Win 10 is only 1/2 finished and I loose my L2 disk cache each time I boot it, so I rarely do. What about other menus? Which Theme are you using?

![image](https://user-images.githubusercontent.com/15389810/145158909-236da053-ab73-431d-bb93-b4d3504cfe4e.png)
![image](https://user-images.githubusercontent.com/15389810/145159280-a3b0d515-20a3-4a98-9c1d-9bd9a692cd43.png)

**Comment by mzso** [comment]
@mzso 
Well, the empty items are fixed now. But the icon positions are still wrong, and I still get scroll buttons.

Could OS DPI settings be an issue again?

**Comment by B00ze64** [comment]
Yeah, I tried it just now @ 125% and 150% and the menus become too big and scroll appears. Not only that, the icons are not positioned properly either. Wasn't this working correctly before v95? All the PANELS are working ok, but not the menus. I'll look at Firefox-UI-Fix, see how they do it (if I recall they use background property instead of ::Before).

**Comment by mzso** [comment]
[**@B00ze64**](https://github.com/B00ze64) commented on [2021. dec. 14. 03:35 CET](https://github.com/B00ze64/FF-Menu-Icon-Plus-CSS/issues/9#issuecomment-993099662 "2021-12-14T02:35:39Z - Replied by Github Reply Comments"):
> Yeah, I tried it just now @ 125% and 150% and the menus become too big and scroll appears. Not only that, the icons are not positioned properly either. Wasn't this working correctly before v95? All the PANELS are working ok, but not the menus. I'll look at Firefox-UI-Fix, see how they do it (if I recall they use background property instead of ::Before).

For me the menus were fine on 88, from which I moved to 95. Now the whole menu style is different. 
Interestingly the hamburger menu icons appear correctly but not any of the context menus'.

**Comment by B00ze64** [comment]
Yeah, I tried in v88 and it works fine, something changed in the way Firefox paints high-DPI menus. but I am not sure how to fix it. I've asked Aris for some ideas.

**Comment by Marvinoo** [comment]
![image](https://user-images.githubusercontent.com/45720537/147188327-bce27840-ffdd-403a-946b-cdb5953f6c90.png)

It's also broken in the latest Nightly build. You can use Nightly build to debug this issue.

**Comment by mzso** [comment]
[**@B00ze64**](https://github.com/B00ze64) commented on [2021. dec. 21. 04:40 CET](https://github.com/B00ze64/FF-Menu-Icon-Plus-CSS/issues/9#issuecomment-998445100 "2021-12-21T03:40:20Z - Replied by Github Reply Comments"):
> Yeah, I tried in v88 and it works fine, something changed in the way Firefox paints high-DPI menus. but I am not sure how to fix it. I've asked Aris for some ideas.

One further thing I noticed, is that the same menu icons look alright for context menus of buttons added via the classic extension Custom Buttons, but not Webextension buttons.
![kép](https://user-images.githubusercontent.com/4479090/147253837-17322f67-46d6-45d7-acc5-502a49907461.png)

**Comment by B00ze64** [comment]
I made adjustments for high DPI, at least the ones I can test (125% and 150%). The icons should be correctly placed, they are for me. The scrolling in the menus is also fixed, but the code for this just started working suddenly, so I have no idea if it will work for you; it works for me at the moment. Get the file from Git here, please let me know if it works for you (altho if it does not work I have no idea what I could do, since it works for me). Thanks.

**Comment by B00ze64** [comment]
PS: media.navigator.enabled must be set to true.

**Comment by mzso** [comment]
[**@B00ze64**](https://github.com/B00ze64) commented on [2021. dec. 28. 06:24 CET](https://github.com/B00ze64/FF-Menu-Icon-Plus-CSS/issues/9#issuecomment-1001876209 "2021-12-28T05:24:58Z - Replied by Github Reply Comments"):
> I made adjustments for high DPI, at least the ones I can test (125% and 150%). The icons should be correctly placed, they are for me. The scrolling in the menus is also fixed, but the code for this just started working suddenly, so I have no idea if it will work for you; it works for me at the moment. Get the file from Git here, please let me know if it works for you (altho if it does not work I have no idea what I could do, since it works for me). Thanks.

Get the file where exactly. There's no new release, and I only see files that are at least 19 days old on github.

**Comment by mzso** [comment]
Okay a found it. The code section showed the 2.4.1 branch by default for some reason.
So I replaced the old MipCSS folder with the new one. It's different, particularly the menubar context menu seems to have more space where the icons are menat to be. But the position of the icons is still wrong:
![kép](https://user-images.githubusercontent.com/4479090/147566058-6446c60f-2f10-43db-b238-a77e067a1ce4.png)
![kép](https://user-images.githubusercontent.com/4479090/147566113-233fd63d-5da9-4a74-b6b2-d78a21da2412.png)

**Comment by B00ze64** [comment]
I'll pack-up a release, works fine for me, I have no idea what you guys are doing but I do not have any issues with the extra code I added at any DPI between 100 and 150%, this is 150% here ->
![image](https://user-images.githubusercontent.com/15389810/147625935-78f1fcaf-32cf-43da-aa16-fa9ffa7df959.png)

**Comment by mzso** [comment]
@B00ze64 
That doesn't look like the proton theme that the browser has by default. That looks like the old style. Even the sub-menu arrows are different.

**Comment by mzso** [comment]
@B00ze64
Even when I switch to "light" theme my menu doesn't look like that. Apart from the different arrows, the menus are rounded and more spacious:
![kép](https://user-images.githubusercontent.com/4479090/147651967-199df356-5e69-43a4-b480-702628915e15.png)

**Comment by Marvinoo** [comment]
> @B00ze64 Even when I switch to "light" theme my menu doesn't look like that. Apart from the different arrows, the menus are rounded and more spacious: ![kép](https://user-images.githubusercontent.com/4479090/147651967-199df356-5e69-43a4-b480-702628915e15.png)

same here, i got roundy corners and can't figure out what happened or how to revert it back to the old square style

**Comment by mzso** [comment]
[**@Marvinoo**](https://github.com/Marvinoo) commented on [2021. dec. 29. 13:27 CET](https://github.com/B00ze64/FF-Menu-Icon-Plus-CSS/issues/9#issuecomment-1002570966 "2021-12-29T12:27:49Z - Replied by Github Reply Comments"):

> same here, i got roundy corners and can't figure out what happened or how to revert it back to the old square style

I don't think it's possible, without some XUL extensions or massive userchrome.js hacking. Even when I set proton to false it appears like this, even with the normal stable branch. Maybe @B00ze64 uses some other version?

**Comment by B00ze64** [comment]
It's possible the menus are different on Win10 versus Win7; I edit the spacing of the menus, but nothing else, and definitively not the corners. I'm going to have to put this on hold until I switch to Win10 I guess. Try changing **--menu-label-margin** to 0px, it looks like the CSS is pulling the label backwards too much in your screenshots.

I have proton enabled...
![image](https://user-images.githubusercontent.com/15389810/147716599-d751251f-279e-4877-8f12-df37a73446e4.png)

**Comment by mzso** [comment]
@B00ze64 
I wonder if there's a way to convince FF that it is running on Win10. From experience comparability mode doesn't help.
With `--menu-label-margin: 0px;` it looks like this:
![kép](https://user-images.githubusercontent.com/4479090/147822099-8c261e34-756b-4e2b-a923-6234cd8d9114.png)
Which I guess is an improvement, though scroll arrows still suck.

**Comment by B00ze64** [comment]
Hahaha, better but not quite there. So the icon itself needs a negative offset, try with **--menu-icon-margin** set to -24px, see if that brings the icon in line with the rest (at 150% the icons are 24x24). As for the scroll arrows, I have no idea why it's still doing it - there is a **min-height** that I set at the top of the CSS, I give it 24px because that is the height of the icons, but maybe it has to be bigger on Win10?

**Comment by mzso** [comment]
@B00ze64 
Well...:
![kép](https://user-images.githubusercontent.com/4479090/147849094-87fbf121-e1a2-452c-963a-bfc3027a3d08.png)
Rather hopless like this. I guess I'll have to make do without icons for now.

**Comment by B00ze64** [comment]
Much better, but the checkmark got moved too, strange that it was working correctly at all and now it's pulled back. So obviously Firefox is building the menus on Win10 differently than on Win7. I'll see about making adding Win10 rules. Thanks for your help.

**Comment by gabri25ele** [comment]
I confimed, something wrong with **Firefox 95.0.2**

![Senza titolo](https://user-images.githubusercontent.com/33927879/148947948-6b2becde-cd4e-40c9-a60e-f8280dd84a16.png)

tried with an older Firefox version and the problem is not present.

**Comment by B00ze64** [comment]
Yes, I have this all fixed already (I installed FF in Win10) but still working on it, especially those menu-too-high arrows, which are caused because in Win10 the menu items are 15 pixels high, not 16 like on Win7, and my icons are 16x16...

**Comment by gabri25ele** [comment]
> Yes, I have this all fixed already (I installed FF in Win10) but still working on it, especially those menu-too-high arrows, which are caused because in Win10 the menu items are 15 pixels high, not 16 like on Win7, and my icons are 16x16...

Win7? 
still exist? 😁

**Comment by B00ze64** [comment]
Alright, v2.6 is out with fixes for Win10 using variables. Downside is that the variables are unDefined for Linux and Mac, so this will not work on those O/S'es. Try it out, see if I've forgotten something, let me know how it works for you.

**Comment by rxpsych** [comment]
Thank you for the updates. This did a fantastic job of fixing the menu problems. One quick question, though. Which parameter has to be adjusted to make the menu items more compact. They are a little too expanded (vertically) and I want to see more bookmarks or menu items at once at once. Thank you.

**Comment by mzso** [comment]
It looks fine here as well..

**Comment by B00ze64** [comment]
> Thank you for the updates. This did a fantastic job of fixing the menu problems. One quick question, though. Which parameter has to be adjusted to make the menu items more compact? They are a little too expanded (vertically) and I want to see more bookmarks or menu items at once at once. Thank you.

I use this in userChrome.css at the end of it:
```css
@media (-moz-os-version: windows-win10) or (-moz-os-version: windows-win11) {

	:root { --arrowpanel-menuitem-padding: 4px 8px !important; }
	menupopup > menuitem, menupopup > menu { padding-block: 2px !important; }
}
```

**Comment by B00ze64** [comment]
@mzso I use a ton of custom buttons in TB60 from codefish.org, but never used the ones you are using. So this is when you right-click one of the buttons? You'd have to attach a AddOn for a button for me to troubleshoot, the Russian site thread is ~560 pages long and I rely on translation too...

**Comment by rxpsych** [comment]
@B00ze64 -  Thank you so much for the information. I did as you said, and then changed the numbers to 2px and 4px. It worked wonderfully. I have noticed though that the folders on my bookmarks toolbar are still expanded as before. Is there a different statement for the bookmarks toolbar folders? Thank you.

**Comment by B00ze64** [comment]
@rxpsych Nope, should work even for the bookmarks menu, folders there are still menuitems as far as I know...

**Comment by rxpsych** [comment]
Thank you for that important information. I have a lot of additional css tweaks added in from https://github.com/Aris-t2/CustomCSSforFx and others. I'm sure one of my other parameters is over-riding the bookmarks toolbar folder spacing. I know very little about CSS, but might you know which parameter specifically adjusts that vertical spacing. Maybe I can search for it.
